name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    paths:
    - 'src/**'
    - '.github/**'

  schedule:
    - cron:  '0 1 * * *'

jobs:
  ubuntu-nightly:
    runs-on: ubuntu-latest
    steps:
    - name: Build
      shell: bash
      run: |
        cmake .
        make
        make install
    - name: Test
      shell: bash
      run: ctest
