name: CI

on:
  pull_request:
    paths:
    - 'src/**'

  schedule:
    - cron:  '0 1 * * *'

  workflow_dispatch:

jobs:
  ubuntu-nightly:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    container:
      image: frolvlad/alpine-gxx
      options: --user 1001
    - name: Build
      shell: bash
      run: |
        cmake .
        make
        make install
        ctest
