name: CI

on:
  pull_request:
    paths:
    - 'src/**'
    - '.github/**'

  schedule:
    - cron:  '0 1 * * *'

jobs:
  ubuntu-nightly:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    container:
      image: frolvlad/alpine-gxx
      options: --user 1001
    steps:
    - name: Build
      shell: bash
      run: |
        cmake .
        make
        make install
    - name: Test
      shell: bash
      run: |
        ctest
